# -*- coding: utf-8 -*-
"""pixel_intensities.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zaTaMRxidj-6kL5Vhutj0JzHu2Uyml4j
"""

# Libraries
from matplotlib import pyplot as plt
import matplotlib
import numpy as np
import skimage as ski
import os
from scipy import ndimage as ndi
from PIL import Image, ImageOps
import seaborn as sns

# function to collect image means from multiple directories
def collect_means(dir_coll):
  means = []
  for dir in dir_coll:
    for filename in os.listdir(dir):
      # open individual image
      img = Image.open(dir + '/' + filename)
      img_arr = np.asarray(img)
      del img

      # calculate mean and store in list
      img_mean = np.mean(img_arr)
      means += [img_mean]

  return means

# list of directories for training sets
o_0_0 = '/content/drive/MyDrive/ORF 498/ORIGA_ROI/train/0'
o_0_1 = '/content/drive/MyDrive/ORF 498/ORIGA_ROI/train/1'
o = [o_0_0, o_0_1]

r_0_0 = '/content/drive/MyDrive/ORF 498/REFUGE_ROI/train/0'
r_0_1 = '/content/drive/MyDrive/ORF 498/REFUGE_ROI/train/1'
r = [r_0_0, r_0_1]

a_0_0 = '/content/drive/MyDrive/ORF 498/ACRIMA_ROI/train/0'
a_0_1 = '/content/drive/MyDrive/ORF 498/ACRIMA_ROI/train/1'
a = [a_0_0, a_0_1]

ro_0_0 = '/content/drive/MyDrive/ORF 498/RIM-ONE_ROI/train/0'
ro_0_1 = '/content/drive/MyDrive/ORF 498/RIM-ONE_ROI/train/1'
ro = [ro_0_0, ro_0_1]

# collect mean of each training set
o_means = collect_means(o)
r_means = collect_means(r)
a_means = collect_means(a)
ro_means = collect_means(ro)

# show and save KDE plot of training set means
plt.rcParams["figure.figsize"] = [6.4,4.8]
sns.set_style("white")
sns.kdeplot(r_means, label='REFUGE', color='red', common_norm=True, fill=True, alpha=0.3, multiple="layer")
sns.kdeplot(ro_means, label='RIM-ONE', color='blue', common_norm=True, fill=True, alpha=0.3, multiple="layer")
sns.kdeplot(o_means, label='ORIGA', color='orange', common_norm=True, fill=True, alpha=0.4, multiple="layer")
sns.kdeplot(a_means, label='ACRIMA', color='green', common_norm=True, fill=True, alpha=0.4, multiple="layer")
plt.title('Average Pixel Intensities of ROI Images')
plt.xlabel("Intensity")
plt.legend()
plt.savefig('/content/drive/MyDrive/ORF 498/ROI_pixel_histograms.png')
plt.show()